name: pipes_online
description: A new Flutter project.
#flutter varsion : 2.10.2
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  sizer: ^2.0.15
  google_fonts: ^3.0.1
  flutter_svg:
  cloud_firestore:
  firebase_core:
  firebase_auth: ^1.0.3
  flutter_signin_button:
  google_sign_in: ^5.2.4
  smooth_star_rating_null_safety: ^1.0.4+2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  share_plus: ^4.0.3
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.2
  fl_chart: ^0.46.0
  geolocator: 8.0.5
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.3
  flutter_progress_hud: ^2.0.0
  image_picker: ^0.8.2
  dio: ^4.0.0
  get_storage: any
  pinput: ^2.2.7
  firebase_storage: ^10.2.9
  uuid: ^3.0.6
  path_provider: ^2.0.9
  file_picker: ^4.5.1
  open_file: ^3.2.1
  cupertino_icons: ^1.0.2
  octo_image: ^1.0.1
  cached_network_image: ^3.2.0
  permission_handler: ^8.3.0
  firebase_messaging: ^11.2.12
  flutter_local_notifications: ^9.4.0
  intl: ^0.17.0
  shimmer: ^2.0.0
  webview_flutter: ^3.0.4
  http_auth: ^1.0.1
  flutter_stripe: ^3.1.0
  #GEO
  #  flutter_polyline_points: ^1.0.0
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/icon/
    - assets/json/

  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf

    #    - family: Ubuntu-Bold
    #      fonts:
    #        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
