name: pipes_online
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get:
  sizer: ^2.0.15
  lottie: ^1.2.2
  google_fonts:
  flutter_svg:
  cloud_firestore:
  firebase_core:
  firebase_auth: ^1.0.3
  flutter_signin_button:
  google_sign_in: ^5.2.4
  carousel_slider: ^4.0.0
  smooth_star_rating_null_safety: ^1.0.4+2
  shared_preferences: ^2.0.13
  url_launcher: ^6.0.20
  share:
  country_code_picker: ^2.0.2
  otp_text_field: ^1.1.2
  fl_chart: ^0.46.0
  geolocator: 8.0.5
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.3
  flutter_progress_hud: ^2.0.0
  image_picker: ^0.8.2
  dio: ^4.0.0
  get_storage: any
#  whats up
  flutter_share: ^2.0.0
  file_picker: ^4.5.1
  open_file: ^3.2.1
#share option
  flutter_phone_direct_caller: ^2.1.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

#  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/svg/
    - assets/images/png/
    - assets/images/icon/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu-Bold
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf

#    - family: Ubuntu-Bold
#      fonts:
#        - asset: assets/fonts/Ubuntu-Bold.ttf

    - family: Ubuntu-Regular
      fonts:
        - asset: assets/fonts/Ubuntu-Regular.ttf

    - family: Ubuntu-Medium
      fonts:
        - asset: assets/fonts/Ubuntu-Medium.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
